### ISSUE TITLE
problems on deit_base_patch16_224_KAN

### ISSUE THREAD

**Issue by tang1-a11y** [chenziwenhaoshuai/Vision-KAN#21]
When I use `torch.load('./KAN_768/best_checkpoint.pth', map_location=torch.device('cpu'))`, an error occurs.

**Comment by tang1-a11y** [comment]
![微信图片_20241031](https://github.com/user-attachments/assets/08d64af5-9bf6-4e8e-afb7-7d03550a56a6)

**Comment by chenziwenhaoshuai** [comment]
Maybe your checkpoint file is corrupted, please try to download it again
