### ISSUE TITLE
NotImplementedError: Module [ModuleList] is missing the required "forward" function

### ISSUE THREAD

**Issue by avBuffer** [chenziwenhaoshuai/Vision-KAN#3]
(kan) jalymo@VoAI:/mnt/d/workspace/pykan/examples/Vision-KAN$ python main.py
/mnt/d/workspace/pykan/examples/Vision-KAN/models_kan.py:152: UserWarning: Overwriting deit_tiny_patch16_224 in registry with models_kan.deit_tiny_patch16_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  @register_model
/mnt/d/workspace/pykan/examples/Vision-KAN/models_kan.py:167: UserWarning: Overwriting deit_small_patch16_224 in registry with models_kan.deit_small_patch16_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  @register_model
/mnt/d/workspace/pykan/examples/Vision-KAN/models_kan.py:182: UserWarning: Overwriting deit_base_patch16_224 in registry with models_kan.deit_base_patch16_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  @register_model
/mnt/d/workspace/pykan/examples/Vision-KAN/models_kan.py:197: UserWarning: Overwriting deit_tiny_distilled_patch16_224 in registry with models_kan.deit_tiny_distilled_patch16_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  @register_model
/mnt/d/workspace/pykan/examples/Vision-KAN/models_kan.py:212: UserWarning: Overwriting deit_small_distilled_patch16_224 in registry with models_kan.deit_small_distilled_patch16_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  @register_model
/mnt/d/workspace/pykan/examples/Vision-KAN/models_kan.py:227: UserWarning: Overwriting deit_base_distilled_patch16_224 in registry with models_kan.deit_base_distilled_patch16_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  @register_model
/mnt/d/workspace/pykan/examples/Vision-KAN/models_kan.py:242: UserWarning: Overwriting deit_base_patch16_384 in registry with models_kan.deit_base_patch16_384. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  @register_model
/mnt/d/workspace/pykan/examples/Vision-KAN/models_kan.py:257: UserWarning: Overwriting deit_base_distilled_patch16_384 in registry with models_kan.deit_base_distilled_patch16_384. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  @register_model
Not using distributed mode
Namespace(batch_size=144, epochs=300, bce_loss=False, unscale_lr=True, model='deit_tiny_patch16_224', input_size=224, drop=0.0, drop_path=0.05, model_ema=True, model_ema_decay=0.99996, model_ema_force_cpu=False, opt='adamw', opt_eps=1e-08, opt_betas=None, clip_grad=None, momentum=0.9, weight_decay=0.05, sched='cosine', lr=0.0005, lr_noise=None, lr_noise_pct=0.67, lr_noise_std=1.0, warmup_lr=1e-06, min_lr=1e-06, decay_epochs=30, warmup_epochs=1, cooldown_epochs=10, patience_epochs=10, decay_rate=0.1, color_jitter=0.3, aa='rand-m9-mstd0.5-inc1', smoothing=0.0, train_interpolation='bicubic', repeated_aug=True, train_mode=True, ThreeAugment=True, src=False, reprob=0.0, remode='pixel', recount=1, resplit=False, mixup=0.8, cutmix=1.0, cutmix_minmax=None, mixup_prob=1.0, mixup_switch_prob=0.5, mixup_mode='batch', teacher_model='regnety_160', teacher_path='', distillation_type='none', distillation_alpha=0.5, distillation_tau=1.0, cosub=False, finetune='', attn_only=False, data_path='./data', data_set='CIFAR', inat_category='name', output_dir='./output', device='cuda', seed=0, resume='', start_epoch=0, eval=False, eval_crop_ratio=1, dist_eval=False, num_workers=10, pin_mem=True, distributed=False, world_size=1, dist_url='env://')
/home/jalymo/.local/lib/python3.11/site-packages/torch/utils/data/dataloader.py:558: UserWarning: This DataLoader will create 10 worker processes in total. Our suggested max number of worker in current system is 8, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Creating model: deit_tiny_patch16_224
number of params: 1240228
Start training for 300 epochs
Traceback (most recent call last):
  File "/mnt/d/workspace/pykan/examples/Vision-KAN/main.py", line 436, in <module>
    main(args)
  File "/mnt/d/workspace/pykan/examples/Vision-KAN/main.py", line 375, in main
    train_stats = train_one_epoch(
                  ^^^^^^^^^^^^^^^^
  File "/mnt/d/workspace/pykan/examples/Vision-KAN/engine.py", line 47, in train_one_epoch
    outputs = model(samples)
              ^^^^^^^^^^^^^^
  File "/home/jalymo/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalymo/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalymo/.local/lib/python3.11/site-packages/timm/models/vision_transformer.py", line 760, in forward
    x = self.forward_features(x)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalymo/.local/lib/python3.11/site-packages/timm/models/vision_transformer.py", line 744, in forward_features
    x = self.blocks(x)
        ^^^^^^^^^^^^^^
  File "/home/jalymo/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalymo/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalymo/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 351, in _forward_unimplemented
    raise NotImplementedError(f"Module [{type(self).__name__}] is missing the required \"forward\" function")
NotImplementedError: Module [ModuleList] is missing the required "forward" function

**Comment by chenziwenhaoshuai** [comment]
What is your timm version?

**Comment by chouheiwa** [comment]
By use this PR, I think this issue can be closed. @avBuffer .
